namespace csh2tscc;

/// <summary>
/// Constants used in TypeScript code generation.
/// </summary>
public static class TypeScriptConstants
{
    // File header
    public const string AutoGeneratedHeader = "//This file is AUTOGENERATED!!! All manual changes will be lost after regeneration.";

    // TypeScript keywords and constructs
    public const string ExportEnum = "export enum";
    public const string ExportInterface = "export interface";

    // TypeScript types
    public const string NumberType = "number";
    public const string BooleanType = "boolean";
    public const string StringType = "string";
    public const string UnknownType = "unknown";

    // Type modifiers
    public const string NullableUnion = " | null";
    public const string OptionalProperty = "?";
    public const string ArraySuffix = "[]";

    // Generic type formatting
    public const char GenericOpen = '<';
    public const char GenericClose = '>';
    public const string GenericSeparator = ", ";
    public const string MapType = "Map";

    // Import statement format: {0} = type name
    public const string ImportFormat = "import {{ {0} }} from \"./{0}\";";

    // Character used to identify compiler-generated types
    public const char CompilerGeneratedTypeIndicator = '<';

    // Generic type name separator (backtick followed by arity number)
    public const char GenericAritySeparator = '`';

    //File footer
    public const string Name = "C# to TypeScript class converter";
    public const string Version = "version 1.0.0";
}

/// <summary>
/// Constants for nullable attribute handling.
/// </summary>
public static class NullabilityConstants
{
    /// <summary>
    /// Byte value indicating a type or member is nullable.
    /// </summary>
    public const byte Nullable = 2;

    /// <summary>
    /// Byte value indicating a type or member is non-nullable.
    /// </summary>
    public const byte NonNullable = 1;

    /// <summary>
    /// Index in the nullable flags array where the property type's own nullability is stored.
    /// </summary>
    public const int PropertyTypeIndex = 0;

    /// <summary>
    /// Starting index for generic argument nullability flags.
    /// Index 0 is the property type itself, so generic args start at 1.
    /// </summary>
    public const int FirstGenericArgIndex = 1;
}

/// <summary>
/// Constants for well-known namespaces and attribute names.
/// </summary>
public static class WellKnownNames
{
    public const string SystemTextJsonNamespace = "System.Text.Json";
    public const string NullableAttributeName = "System.Runtime.CompilerServices.NullableAttribute";
    public const string NullableContextAttributeName = "System.Runtime.CompilerServices.NullableContextAttribute";
}
