using System.Reflection;
using System.Text.Json.Serialization;

namespace csh2tscc;

internal class TypeScriptBuilder(TypesGeneratorParameters parameters, TypeResolver resolver, TypeDiscovery discovery)
{
    private record AttributeProcessingResult(string Name, bool IsBlocked);

    private const string MemberIndent = "  ";

    private readonly XmlDocProvider _docs = new();

    private static readonly string? Title = typeof(TypeScriptBuilder).Assembly.GetCustomAttribute<AssemblyTitleAttribute>()?.Title;
    private static readonly string? Version = typeof(TypeScriptBuilder).Assembly.GetName().Version?.ToString();
    internal string BuildFileFromType(Type typeToWrite)
    {
        var sb = new StringBuilderCustom(parameters.Verbose);
        sb.AppendDebugLine("Debug mode");
        sb.AppendDebugLine($"{Title} v{Version}");
        sb.AppendLine(TypeScriptConstants.AutoGeneratedHeader);
        sb.AppendLine();
        sb = typeToWrite.IsEnum ? BuildFromEnum(typeToWrite, sb) : BuildFromClass(typeToWrite, sb);
        return sb.ToString();
    }

    private StringBuilderCustom BuildFromEnum(Type typeToWrite, StringBuilderCustom sb)
    {
        AppendDoc(sb, _docs.ForType(typeToWrite), string.Empty);
        sb.AppendLine($"{TypeScriptConstants.ExportEnum} {TypeNameHelper.GetTypeScriptName(typeToWrite, parameters.UseFullNames)} {{");
        var fields = typeToWrite.GetFields(BindingFlags.Static | BindingFlags.Public);
        foreach (var field in fields)
        {
            sb.AppendDebugLine($"Default field name [{field.Name}]");
            var attributes = field.GetCustomAttributes().ToList();
            var result = ProcessMemberAttributes(attributes, field.Name, typeToWrite, sb);

            if (result.IsBlocked)
            {
                sb.AppendDebugLine($"Serialization of the property [{field.Name}] is blocked");
                continue;
            }

            var quote = TypeScriptConstants.StringQuote;
            AppendDoc(sb, _docs.ForMember(field), MemberIndent);
            sb.AppendLine($"{MemberIndent}{field.Name} = {quote}{EscapeQuoted(result.Name)}{quote},");
        }

        sb.AppendLine('}');
        return sb;
    }

    private StringBuilderCustom BuildFromClass(Type typeToWrite, StringBuilderCustom sb)
    {
        var affected = discovery.ListAffectedTypes(typeToWrite).ToList();
        var genericParameters = typeToWrite.IsGenericType ? typeToWrite.GetGenericArguments() : [];
        var genericHeader = genericParameters.Length == 0
            ? string.Empty
            : $"{TypeScriptConstants.GenericOpen}{string.Join(TypeScriptConstants.GenericSeparator, genericParameters.Select(x => x.Name))}{TypeScriptConstants.GenericClose}";
        var ownName = TypeNameHelper.GetNormalizedTypeScriptName(typeToWrite, parameters.UseFullNames);
        var importsAdded = false;
        foreach (var affType in affected)
        {
            var importName = TypeNameHelper.GetNormalizedTypeScriptName(affType, parameters.UseFullNames);

            // Comparing by emitted name (not by Type identity) also catches recursive generics:
            // TreeNode<T> referencing TreeNode<T> is a constructed type != the open definition,
            // yet importing the file from itself would be invalid.
            if (importName == ownName)
            {
                continue;
            }

            var format = affType.IsEnum
                ? TypeScriptConstants.ImportFormat
                : TypeScriptConstants.ImportTypeFormat;
            sb.AppendLine(string.Format(format, importName));
            importsAdded = true;
        }

        if (importsAdded)
        {
            sb.AppendLine();
        }

        AppendDoc(sb, _docs.ForType(typeToWrite), string.Empty);
        sb.AppendLine($"{TypeScriptConstants.ExportInterface} {ownName}{genericHeader} {{");

        var properties = CommonHelper.GetSerializableProperties(typeToWrite);

        foreach (var property in properties)
        {
            var defaultName = TypeNameHelper.ToCamelCase(property.Name, parameters.CamelCaseProperties);
            sb.AppendDebugLine($"Default field name [{defaultName}]");
            var attributes = property.GetCustomAttributes().ToList();
            var result = ProcessMemberAttributes(attributes, defaultName, typeToWrite, sb, throwOnNullName: true);

            if (result.IsBlocked)
            {
                sb.AppendDebugLine($"Serialization of the property [{property.Name}] is blocked");
                continue;
            }

            var isNullableByDefinition = IsNullableHelper.IsNullable(typeToWrite, property);
            if (isNullableByDefinition)
            {
                sb.AppendDebugLine("Property is nullable by definition");
            }

            var hasNotNullableAttribute = CommonHelper.HasNonNullableAttribute(property);
            if (hasNotNullableAttribute)
            {
                sb.AppendDebugLine("Property has non-nullable attribute");
            }

            var isNullable = isNullableByDefinition && !hasNotNullableAttribute;
            var context = new PropertyTypeExtractionContext
            {
                ClassToWrite = typeToWrite,
                PropInfo = property,
                PropertyType = property.PropertyType,
                AffectedTypes = affected,
                GenericTypes = genericParameters,
                SuppressNullable = hasNotNullableAttribute,
                BooleanContainer = null,
                IsNullable = isNullable
            };
            AppendDoc(sb, _docs.ForMember(property), MemberIndent);
            sb.AppendLine($"{MemberIndent}{result.Name}{(isNullable && parameters.OptionalNullableProperties ? TypeScriptConstants.OptionalProperty : string.Empty)}: {resolver.ResolveTypeToTypeScript(context)};");
        }

        sb.AppendLine('}');
        return sb;
    }

    private AttributeProcessingResult ProcessMemberAttributes(
        IList<Attribute> attributes,
        string defaultName,
        Type parentType,
        StringBuilderCustom sb,
        bool throwOnNullName = false)
    {
        var name = defaultName;
        var nameAttributeCount = 0;
        var isBlocked = false;

        foreach (var attribute in attributes)
        {
            var attributeType = attribute.GetType();

            // Check for serialization naming attributes
            if (parameters.SerializationNamingAttributes.TryGetValue(attributeType.Name, out var attributePropertyName))
            {
                ++nameAttributeCount;
                var prop = attributeType.GetProperty(attributePropertyName)
                    ?? throw new AttributeProcessingException(
                        $"No property name [{attributePropertyName}] for type [{attributeType.Name}]",
                        attributeType.Name, defaultName, parentType);

                var extractedName = prop.GetValue(attribute, null)?.ToString();
                if (extractedName == null && throwOnNullName)
                {
                    throw new AttributeProcessingException(
                        $"Property name [{attributePropertyName}] for type [{attributeType.Name}] is null",
                        attributeType.Name, defaultName, parentType);
                }

                name = extractedName ?? name;
                sb.AppendDebugLine($"New field name is [{name}] from attribute [{attributePropertyName}]");
            }

            // Check for no-serialization attributes
            var attributeFromNoSerializingList = parameters.NoSerializationAttributes.SingleOrDefault(x => x == attributeType.Name);
            switch (attributeFromNoSerializingList)
            {
                case null:
                    continue;
                case nameof(JsonIgnoreAttribute)
                    when (attributeType.FullName?.StartsWith(WellKnownNames.SystemTextJsonNamespace) ?? false):
                    {
                        var jic = (JsonIgnoreCondition)attributeType.GetProperty("Condition")!.GetValue(attribute, null)!;
                        sb.AppendDebugLine($"Found attribute [{attributeType.Name}] condition is [{jic}]");
                        if (jic == JsonIgnoreCondition.Always)
                        {
                            isBlocked = true;
                        }
                        break;
                    }
                default:
                    sb.AppendDebugLine($"Found attribute [{attributeType.Name}]");
                    isBlocked = true;
                    break;
            }
        }

        if (nameAttributeCount > 1)
        {
            throw new InvalidSerializationConfigException(
                $"Property name [{name}] of type [{parentType}] has more than one serialization naming attribute");
        }

        return new AttributeProcessingResult(name, isBlocked);
    }

    private void AppendDoc(StringBuilderCustom sb, string? block, string indent)
    {
        if (!parameters.GenerateJsDoc || block == null)
        {
            return;
        }

        sb.AppendLine(XmlDocProvider.Indent(block, indent));
    }

    /// <summary>
    /// Escapes a value for embedding into a TypeScript string literal quoted with
    /// <see cref="TypeScriptConstants.StringQuote"/>.
    /// </summary>
    private static string EscapeQuoted(string value) =>
        value.Replace("\\", "\\\\").Replace($"{TypeScriptConstants.StringQuote}", $"\\{TypeScriptConstants.StringQuote}");
}
