using csh2tscc;

namespace tests.TestSupport;

/// <summary>
/// Shared assertions about generated TypeScript output, previously duplicated across the
/// integration tests.
/// </summary>
public static class TsAssertions
{
    /// <summary>
    /// Asserts a generated file is well-formed: it uses the expected extension, carries the
    /// auto-generated header, and does not end with a trailing blank line
    /// (see the StringBuilderCustom fix).
    /// </summary>
    public static void AssertGeneratedFileWellFormed(string fileName, string content, string expectedExtension = ".tsx")
    {
        Assert.EndsWith(expectedExtension, fileName);
        Assert.Contains(TypeScriptConstants.AutoGeneratedHeader, content);
        Assert.False(content.EndsWith(Environment.NewLine + Environment.NewLine),
            $"Generated TypeScript for '{fileName}' has a trailing blank line.");
    }

    /// <summary>Asserts that none of the generated file keys contain any of the forbidden fragments.</summary>
    public static void AssertNoKeysContain(IEnumerable<string> keys, params string[] forbiddenFragments)
    {
        var keyList = keys.ToList();
        foreach (var fragment in forbiddenFragments)
        {
            Assert.DoesNotContain(keyList, k => k.Contains(fragment));
        }
    }
}
