using csh2tscc;
using Dto.Integration.Tests.DTO.Extensions;
using System.Collections.Frozen;
using System.Text.Json.Serialization;

namespace tests;

public class TypesGeneratorIntegrationTests(ITestOutputHelper testOutputHelper)
{
    [Theory]
    [InlineData("", false)]
    [InlineData(".Generics.SimpleGenerics", false)]
    [InlineData(".Generics.Enumerable", false)]
    [InlineData(".Generics.MultiGenerics", false)]
    [InlineData(".Required", false)]
    [InlineData(".Nullability", false)]
    [InlineData(".NonExisting", true, "ExportTestAttribute")]
    public void TestDryGeneration(string subpath, bool emptyOk, string? exportAttribute = null)
    {
        var config = new TypesGeneratorParameters
        {
            CamelCaseProperties = true,
            LibraryFileNames = ["Dto.Integration.Tests.dll"],
            RootNamespaces = ["Dto.Integration.Tests.DTO" + subpath],
            RootNamespacesExcluded = ["Dto.Integration.Tests.DTO.Extensions"],
            SerializationNamingAttributes = new Dictionary<string, string> { { nameof(JsonStringEnumMemberNameAttribute), "Name" }, { nameof(CustomNameAttribute), "CustomName" } }.ToFrozenDictionary(),
            NoSerializationAttributes = [nameof(JsonIgnoreAttribute), nameof(NoSerializeAttribute)],
            ExportAttributes = exportAttribute == null ? [] : [exportAttribute],
            OutputDirectory = "",
            UnknownTypesToString = true,
            Verbose = true
        };
        var generator = new TypesGenerator(config);
        var types = generator.TransformTypes();
        foreach (var type in types)
        {
            testOutputHelper.WriteLine(type.Key);
            testOutputHelper.WriteLine(type.Value);
            testOutputHelper.WriteLine("=====================================================");
        }

        // The .NonExisting namespace has no types — emptyOk allows that case.
        // When ExportTestAttribute is set, only [ExportTest]-marked types must appear.
        if (!emptyOk)
        {
            Assert.NotEmpty(types);
        }

        if (exportAttribute == "ExportTestAttribute")
        {
            Assert.Contains(types.Keys, k => k.StartsWith("WebhookBase"));
            Assert.Contains(types.Keys, k => k.StartsWith("WebHookTestEnum"));
        }

        // Every generated file must carry the auto-generated header and end cleanly
        // (no trailing blank line — see StringBuilderCustom fix).
        foreach (var (key, value) in types)
        {
            Assert.EndsWith(".tsx", key);
            Assert.Contains(TypeScriptConstants.AutoGeneratedHeader, value);
            Assert.False(value.EndsWith(Environment.NewLine + Environment.NewLine),
                $"Generated TypeScript for '{key}' has a trailing blank line.");
        }

        // No type from the excluded namespace must leak into the output.
        Assert.DoesNotContain(types.Keys, k =>
            k.Contains("CustomNameAttribute") || k.Contains("NoSerializeAttribute") || k.Contains("ILocationRequest"));
    }

    [Fact]
    public void FullTest()
    {
        var generator = new TypesGenerator(new TypesGeneratorParameters
        {
            CamelCaseProperties = true,
            LibraryFileNames = ["Dto.Integration.Tests.dll"],
            RootNamespaces = ["Dto.Integration.Tests.DTO"],
            RootNamespacesExcluded = ["Dto.Integration.Tests.DTO.Extensions"],
            SerializationNamingAttributes = new Dictionary<string, string> { { nameof(JsonStringEnumMemberNameAttribute), "Name" }, { nameof(CustomNameAttribute), "CustomName" } }.ToFrozenDictionary(),
            NoSerializationAttributes = [nameof(JsonIgnoreAttribute), nameof(NoSerializeAttribute)],
            UseFullNames = false,
            FileExtension = ".tsx",
            CleanOutputDirectory = true,
            OutputDirectory = "./generated",
            Verbose = true
        });
        Directory.CreateDirectory(generator.Config.OutputDirectory);
        if (generator.Config.CleanOutputDirectory)
        {
            foreach (var file in new DirectoryInfo(generator.Config.OutputDirectory).EnumerateFiles($"*{generator.Config.FileExtension}"))
            {
                file.Delete();
            }
        }

        var tsClasses = generator.TransformTypes();
        var count = 0;
        foreach (var tsClass in tsClasses)
        {
            File.WriteAllText($"{generator.Config.OutputDirectory}/{tsClass.Key}", tsClass.Value);
            ++count;
            testOutputHelper.WriteLine($"File [{tsClass.Key}] created");
        }
        testOutputHelper.WriteLine($"[{count}] file(s) generated");

        Assert.NotEmpty(tsClasses);
        Assert.Equal(tsClasses.Count, count);

        // Every emitted file lands on disk with the configured extension.
        var onDisk = Directory.EnumerateFiles(generator.Config.OutputDirectory, $"*{generator.Config.FileExtension}")
            .Select(Path.GetFileName)
            .ToHashSet(StringComparer.Ordinal);
        Assert.Equal(tsClasses.Count, onDisk.Count);

        foreach (var (key, value) in tsClasses)
        {
            Assert.Contains(key, onDisk);
            Assert.Contains(TypeScriptConstants.AutoGeneratedHeader, value);
            Assert.False(value.EndsWith(Environment.NewLine + Environment.NewLine),
                $"Generated TypeScript for '{key}' has a trailing blank line.");
        }

        // A known enum should be emitted with `export enum`.
        var enumFile = tsClasses.Single(kv => kv.Key == "UserRole.tsx");
        Assert.Contains("export enum UserRole", enumFile.Value);

        // Types from the excluded namespace must not appear.
        Assert.DoesNotContain(tsClasses.Keys, k => k.Contains("CustomNameAttribute"));
        Assert.DoesNotContain(tsClasses.Keys, k => k.Contains("NoSerializeAttribute"));
        Assert.DoesNotContain(tsClasses.Keys, k => k.Contains("ILocationRequest"));
    }
}